### ISSUE TITLE
app.on errors when attempting to run.

### ISSUE THREAD

**Issue by ProjectHSI** [Bakuenjin/tetrio-desktop#4]
Error:
D:\Games\tetrio-desktop-master\index.js:40
app.on('activate', async () => {
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (D:\Games\tetrio-desktop-master\index.js:40:5)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1176:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:1040:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:929:14)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)?[39m
?[90m    at internal/main/run_main_module.js:17:47?[39m
Seems like app.on does not exist.

**Comment by ProjectHSI** [comment]
And yes I have installed the modules.

**Comment by ProjectHSI** [comment]
Closed. Message via Discord explaining how for it to work.
